language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dramirezp/docker-react -f Dockerfile.dev .

script:
  - docker run dramirezp/docker-react npm run test --coverage

